server:
  port: 8012
spring:
  application:
    name: api-gateway
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hungdoan-tech/Vivacon-Configuration.git
          username: hungdoan-tech
          password: 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
          clone-on-start: true
          default-label: main
          force-pull: true
        enabled: true
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  config:
#    import: optional:configserver:http://localhost:8012
management:
  endpoints:
    web:
      exposure:
        include: busrefresh