server:
  port: 8012

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/vivacon/configurations/dev
        git:
          uri: https://github.com/hungdoan-tech/Vivacon-Configuration.git
          username: hungdoan-tech
          password: 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
          clone-on-start: true
          default-label: main
          force-pull: true
        enabled: true
    bus:
      enabled: true
      refresh:
        enabled: true
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: busrefresh