server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8012

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,beans,mapping