server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8012
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,beans,mapping

logging:
  level:
    com:
      vivacon:
        user_service:
          data_access: DEBUG
  file:
    name: users-ws.log

